symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600  # Durée de validité du token de réinitialisation (en secondes)
    throttle_limit: 3600  # Temps d'attente entre les demandes de réinitialisation (en secondes)